#!/usr/bin/env python3
"""
Terraform output을 기반으로 .env.development 파일을 생성하는 스크립트

사용법:
    # Dev 환경
    cd infra/environments/dev
    AWS_PROFILE=<your-profile> terraform output -json | python3 ../../../scripts/generate_env_from_terraform.py

    # 또는 직접 실행
    cd infra/environments/dev
    AWS_PROFILE=<your-profile> python3 ../../../scripts/generate_env_from_terraform.py --env dev
"""

import json
import sys
import subprocess
import argparse
from pathlib import Path


# Terraform output key -> .env 변수 매핑
TERRAFORM_TO_ENV_MAPPING = {
    # DynamoDB Tables
    "dynamodb_agent_table": "DYNAMODB_AGENT_TABLE",
    "dynamodb_kb_table": "DYNAMODB_KB_TABLE",
    "dynamodb_kb_versions_table": "DYNAMODB_KB_VERSIONS_TABLE",
    "dynamodb_teamtag_table": "DYNAMODB_TEAMTAG_TABLE",
    "dynamodb_playground_table": "DYNAMODB_PLAYGROUND_TABLE",
    "dynamodb_conversations_table": "DYNAMODB_PLAYGROUND_CONVERSATIONS_TABLE",
    "dynamodb_mcp_table": "DYNAMODB_MCP_TABLE",
    "dynamodb_mcp_versions_table": "DYNAMODB_MCP_VERSIONS_TABLE",
    "dynamodb_api_catalog_table": "DYNAMODB_API_CATALOG_TABLE",
    # S3 Buckets
    "s3_bucket_name": "S3_KB_FILES_BUCKET",
    "playground_sessions_bucket": "PLAYGROUND_SESSIONS_BUCKET",
    "agent_build_source_bucket": "AGENT_BUILD_SOURCE_BUCKET",
    # ECR
    "ecr_repository_url": "PLAYGROUND_ECR_REPOSITORY",
    # IAM Roles
    "playground_runtime_role_arn": "PLAYGROUND_RUNTIME_ROLE_ARN",
    "bedrock_kb_role_arn": "BEDROCK_KB_ROLE_ARN",
    # CodeBuild
    "codebuild_project_name": "CODEBUILD_PROJECT_NAME",
    # Base Image
    "base_image_uri": "BASE_IMAGE_URI",
    # SQS
    "kb_creation_queue_url": "SQS_KB_CREATION_QUEUE_URL",
}

# 기본 환경변수 (Terraform output에 없는 값)
DEFAULT_ENV_VALUES = {
    "API_V1_PREFIX": "/api/v1",
    "PROJECT_NAME": "AWS Agentic AI Platform",
    "VERSION": "0.1.0",
    "CORS_ORIGINS": "http://localhost:5173,http://localhost:3000,http://localhost:80",
    "OKTA_ISSUER": "https://amazon-q-poc.oktapreview.com/oauth2/ausrsjy67549AK36Z1d7",
    "OKTA_AUDIENCE": "api://default",
    "OKTA_CLIENT_ID": "0oarshf24kubl6YYF1d7",
    "AWS_REGION": "us-east-1",
    "TABLE_PREFIX": "agentic-ai",
    "BEDROCK_MODEL_ID": "anthropic.claude-3-sonnet-20240229-v1:0",
    "EMBEDDING_MODEL_ARN": "arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v1",
}


def get_terraform_output(env: str, aws_profile: str = None) -> dict:
    """Terraform output을 JSON으로 가져옵니다."""
    script_dir = Path(__file__).parent
    terraform_dir = script_dir.parent / "infra" / "environments" / env

    if not terraform_dir.exists():
        raise FileNotFoundError(f"Terraform directory not found: {terraform_dir}")

    cmd = ["terraform", "output", "-json"]
    env_vars = {}
    if aws_profile:
        env_vars["AWS_PROFILE"] = aws_profile

    import os
    full_env = os.environ.copy()
    full_env.update(env_vars)

    result = subprocess.run(
        cmd,
        cwd=terraform_dir,
        capture_output=True,
        text=True,
        env=full_env,
    )

    if result.returncode != 0:
        raise RuntimeError(f"terraform output failed: {result.stderr}")

    return json.loads(result.stdout)


def parse_terraform_output(tf_output: dict) -> dict:
    """Terraform output을 .env 형식으로 변환합니다."""
    env_vars = {}

    for tf_key, env_key in TERRAFORM_TO_ENV_MAPPING.items():
        if tf_key in tf_output:
            value = tf_output[tf_key]
            if isinstance(value, dict) and "value" in value:
                env_vars[env_key] = value["value"]
            else:
                env_vars[env_key] = value

    return env_vars


def generate_env_file(env_vars: dict, environment: str) -> str:
    """완전한 .env 파일 내용을 생성합니다."""
    lines = [
        f"# Auto-generated from terraform output ({environment} environment)",
        f"# Generated by: scripts/generate_env_from_terraform.py",
        "",
        "# =====================",
        "# API Settings",
        "# =====================",
    ]

    # 기본값 추가
    for key in ["API_V1_PREFIX", "PROJECT_NAME", "VERSION", "CORS_ORIGINS"]:
        value = env_vars.get(key, DEFAULT_ENV_VALUES.get(key, ""))
        lines.append(f"{key}={value}")

    lines.extend([
        "",
        "# =====================",
        "# Okta Settings",
        "# =====================",
    ])
    for key in ["OKTA_ISSUER", "OKTA_AUDIENCE", "OKTA_CLIENT_ID"]:
        value = env_vars.get(key, DEFAULT_ENV_VALUES.get(key, ""))
        lines.append(f"{key}={value}")
    # SKIP_AUTH는 dev 환경에서만 true
    skip_auth_value = "true" if environment == "dev" else "false"
    lines.append(f"SKIP_AUTH={skip_auth_value}")

    lines.extend([
        "",
        "# =====================",
        "# AWS Settings",
        "# =====================",
    ])
    lines.append(f"AWS_REGION={env_vars.get('AWS_REGION', DEFAULT_ENV_VALUES['AWS_REGION'])}")
    lines.append(f"ENVIRONMENT={environment}")
    lines.append(f"TABLE_PREFIX={DEFAULT_ENV_VALUES['TABLE_PREFIX']}")

    lines.extend([
        "",
        "# =====================",
        "# DynamoDB Tables (from Terraform)",
        "# =====================",
    ])
    for key in [
        "DYNAMODB_AGENT_TABLE",
        "DYNAMODB_KB_TABLE",
        "DYNAMODB_KB_VERSIONS_TABLE",
        "DYNAMODB_TEAMTAG_TABLE",
        "DYNAMODB_PLAYGROUND_TABLE",
        "DYNAMODB_PLAYGROUND_CONVERSATIONS_TABLE",
        "DYNAMODB_MCP_TABLE",
        "DYNAMODB_MCP_VERSIONS_TABLE",
        "DYNAMODB_API_CATALOG_TABLE",
    ]:
        value = env_vars.get(key, "")
        lines.append(f"{key}={value}")

    lines.extend([
        "",
        "# =====================",
        "# S3 Buckets (from Terraform)",
        "# =====================",
    ])
    for key in ["S3_KB_FILES_BUCKET", "PLAYGROUND_SESSIONS_BUCKET", "AGENT_BUILD_SOURCE_BUCKET"]:
        value = env_vars.get(key, "")
        lines.append(f"{key}={value}")

    lines.extend([
        "",
        "# =====================",
        "# CodeBuild & ECR (from Terraform)",
        "# =====================",
    ])
    for key in ["CODEBUILD_PROJECT_NAME", "PLAYGROUND_ECR_REPOSITORY", "BASE_IMAGE_URI"]:
        value = env_vars.get(key, "")
        lines.append(f"{key}={value}")

    lines.extend([
        "",
        "# =====================",
        "# IAM Roles (from Terraform)",
        "# =====================",
    ])
    for key in ["PLAYGROUND_RUNTIME_ROLE_ARN", "BEDROCK_KB_ROLE_ARN"]:
        value = env_vars.get(key, "")
        lines.append(f"{key}={value}")

    lines.extend([
        "",
        "# =====================",
        "# SQS (from Terraform)",
        "# =====================",
    ])
    lines.append(f"SQS_KB_CREATION_QUEUE_URL={env_vars.get('SQS_KB_CREATION_QUEUE_URL', '')}")

    lines.extend([
        "",
        "# =====================",
        "# Bedrock Settings",
        "# =====================",
    ])
    for key in ["BEDROCK_MODEL_ID", "EMBEDDING_MODEL_ARN"]:
        value = env_vars.get(key, DEFAULT_ENV_VALUES.get(key, ""))
        lines.append(f"{key}={value}")

    lines.extend([
        "",
        "# =====================",
        "# Optional - Manual Configuration",
        "# =====================",
        "# These values are not from Terraform and need manual configuration if used",
        "APIGEE_API_KEY=",
        "APIGEE_KEY_CREDENTIAL_PROVIDER_ARN=",
        "AMADEUS_API_KEY=",
        "AMADEUS_API_SECRET=",
        "AMADEUS_TOKEN_URL=",
        "AMADEUS_OAUTH_CREDENTIAL_PROVIDER_ARN=",
        "",
    ])

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate .env file from Terraform output"
    )
    parser.add_argument(
        "--env",
        choices=["dev", "prod"],
        default="dev",
        help="Environment (dev or prod)",
    )
    parser.add_argument(
        "--profile",
        help="AWS Profile to use",
    )
    parser.add_argument(
        "--output",
        "-o",
        help="Output file path (default: apps/backend/.env.development)",
    )
    parser.add_argument(
        "--stdin",
        action="store_true",
        help="Read terraform output from stdin (pipe mode)",
    )

    args = parser.parse_args()

    # Terraform output 가져오기
    if args.stdin:
        tf_output = json.load(sys.stdin)
    else:
        print(f"Getting terraform output from {args.env} environment...")
        tf_output = get_terraform_output(args.env, args.profile)

    # 환경변수로 변환
    env_vars = parse_terraform_output(tf_output)

    # .env 파일 생성
    env_content = generate_env_file(env_vars, args.env)

    # 출력 파일 결정
    if args.output:
        output_path = Path(args.output)
    else:
        script_dir = Path(__file__).parent
        output_path = script_dir.parent / "apps" / "backend" / ".env.development"

    # 파일 쓰기
    output_path.write_text(env_content)
    print(f"Generated: {output_path}")


if __name__ == "__main__":
    main()
